#!/bin/bash
set -euo pipefail

# pptx to markdown converter
# Revan Sopher 2014
# Creates folder pptimages and md file with unformatted text and images
# TODO don't destroy formatting

if [ $# -ne 1 ]; then
	echo "Usage $0 <file.pptx>"
	exit 1
fi

temp="/tmp/pptx2md"
output_temp="$temp/$(basename $1)_temp.md"
output="$temp/$(basename $1).md"

#extract file
unzip -oq -d $temp "$1"
if [ $? -ne 0 ]; then
	echo "Failed to extract."
	exit 1
fi

#replace <> with \n, images with placeholder, strip style.visibilitypp
for filename in $(ls "$temp"/ppt/slides/*.xml | sort --version-sort -f); do
	cat $filename | \
  sed -e "s/<p:cNvPr.*name=\"Picture [0-9]\+\".*\/>/\npptx2md PICTURE GOES HERE\n/g" \
        -e 's/<a:buNone\/>\(<[^>]*>\)\+/<a:buNone\/>\n/g' \
	      -e 's/<a:pPr\ lvl="1"\/>\(<[^>]*>\)\+/<a:pPr\/>\n\n### /g' \
        -e 's/<a:pPr\ lvl="2"\/>\(<[^>]*>\)\+/<a:pPr\/>\n\n#### /g' \
        -e 's/<a:pPr\ lvl="3"\/>\(<[^>]*>\)\+/<a:pPr\/>\n\n##### /g' \
        -e 's/<a:pPr\ lvl="4"\/>\(<[^>]*>\)\+/<a:pPr\/>\n\n###### /g' \
        -e 's/<a:pPr\ lvl="5"\/>\(<[^>]*>\)\+/<a:pPr\/>\n\n####### /g' \
        -e 's/<a:pPr\ lvl="6"\/>\(<[^>]*>\)\+/<a:pPr\/>\n\n######## /g' \
        -e '0,/<\/a:rPr>\(<[^>]*>\)\+/s//<\/a:rPr\/>\n\n# /' \
        -e 's/<\/a:rPr>\(<[^>]*>\)\+/<\/a:rPr\/>\n\n## /g' \
        -e 's/\(<[^>]*>\)\+//g' \
	      -e 's/style.visibility\n//g' \
	      >> $output_temp
done

#next, we replace placeholder text with an incrementing image link
imageNum=1
while read line; do
	if echo "$line" | grep -q "pptx2md PICTURE GOES HERE"; then
	  imageName="$(find "${temp}/ppt/media" -name "image${imageNum}.*" -printf "%P")"
		echo "![image](pptimages/${imageName})" >> $output
		imageNum=$((imageNum+1))
	else
		echo "$line" >> "$output"
	fi
done < $output_temp

#copy final files, clean up
cp -rf ${temp}/ppt/media ./pptimages/
cp $output .
rm -rf /tmp/pptx2md
